spring:
  application:
    name: apigateway

  cloud:
    loadbalancer:
      retry:
        enabled: true

    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"

      routes:
        - id: registryservice
          uri: lb://REGISTRYSERVICE
          predicates:
            - Path=/registry/**

        - id: metricservice
          uri: lb://METRICSERVICE
          predicates:
            - Path=/metrics/**

        - id: scalingservice
          uri: lb://SCALINGSERVICE
          predicates:
            - Path=/scaling/**

        - id: failureservice
          uri: lb://FAILURESERVICE
          predicates:
            - Path=/failures/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: "always"