spring.application.name=metricservice
server.port=8082

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=false

spring.cloud.loadbalancer.retry.enabled=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always